<?php
/**
* Message translations.
*
* This file is automatically generated by 'yii translate' command.
* It contains the localizable messages extracted from source code.
* You may modify this file by translating the extracted messages.
*
* Each array element represents the translation (value) of a message (key).
* If the value is empty, the message is considered as not translated.
* Messages that no longer need translation will have their translations
* enclosed between a pair of '@@' marks.
*
* Message string can be used with plural forms format. Check i18n section
* of the guide for details.
*
* NOTE: this file must be saved in UTF-8 encoding.
*/
return [
    'Arabic' => 'αραβικός',
    'Chinese' => 'κινέζικα',
    'Czech' => 'Τσέχος',
    'Dutch' => 'Ολλανδός',
    'English' => 'Αγγλικά',
    'French' => 'γαλλική γλώσσα',
    'German' => 'Γερμανός',
    'Greek' => 'Ελληνικά',
    'Hindi' => 'Χίντι',
    'Indonesian' => 'Ινδονήσιος',
    'Italian' => 'ιταλικός',
    'Japanese' => 'Ιαπωνικά',
    'Korean' => 'κορεάτης',
    'Persian' => 'περσικός',
    'Polish' => 'Στίλβωση',
    'Portuguese' => 'Πορτογαλικά',
    'Russian' => 'Ρωσική',
    'Spanish' => 'Ισπανικά',
    'Swedish' => 'Σουηδικά',
    'Thailand' => 'Ταϊλάνδη',
    'Vietnamese' => 'Βιετναμέζοι',
];