<?php
/**
* Message translations.
*
* This file is automatically generated by 'yii translate' command.
* It contains the localizable messages extracted from source code.
* You may modify this file by translating the extracted messages.
*
* Each array element represents the translation (value) of a message (key).
* If the value is empty, the message is considered as not translated.
* Messages that no longer need translation will have their translations
* enclosed between a pair of '@@' marks.
*
* Message string can be used with plural forms format. Check i18n section
* of the guide for details.
*
* NOTE: this file must be saved in UTF-8 encoding.
*/
return [
    'Thai' => '泰国',
    'Arabic' => '阿拉伯',
    'Chinese' => '中文',
    'Czech' => '捷克',
    'Dutch' => '荷兰语',
    'English' => '英语',
    'French' => '法语',
    'German' => '德语',
    'Greek' => '希腊语',
    'Hindi' => '印地语',
    'Indonesian' => '印度尼西亚',
    'Italian' => '意大利语',
    'Japanese' => '日本',
    'Korean' => '韩语',
    'Persian' => '波斯语',
    'Polish' => '抛光',
    'Portuguese' => '葡萄牙语',
    'Russian' => '俄语',
    'Spanish' => '西班牙语',
    'Swedish' => '瑞典',
    'Vietnamese' => '越南',
];