<?php
/**
* Message translations.
*
* This file is automatically generated by 'yii translate' command.
* It contains the localizable messages extracted from source code.
* You may modify this file by translating the extracted messages.
*
* Each array element represents the translation (value) of a message (key).
* If the value is empty, the message is considered as not translated.
* Messages that no longer need translation will have their translations
* enclosed between a pair of '@@' marks.
*
* Message string can be used with plural forms format. Check i18n section
* of the guide for details.
*
* NOTE: this file must be saved in UTF-8 encoding.
*/
return [
    'Arabic' => 'アラビア語',
    'Chinese' => '中国語',
    'Hindi' => 'ヒンディー語',
    'Japanese' => '日本語',
    'Korean' => '韓国語',
    'Portuguese' => 'ポルトガル語',
    'Dutch' => 'オランダの',
    'English' => '英語',
    'French' => 'フランス語',
    'German' => 'ドイツ人',
    'Italian' => 'イタリアの',
    'Russian' => 'ロシア',
    'Spanish' => 'スペイン語',
    'Persian' => 'ペルシア語',
    'Polish' => '研磨',
    'Vietnamese' => 'ベトナム語',
];
