<?php
/**
* Message translations.
*
* This file is automatically generated by 'yii translate' command.
* It contains the localizable messages extracted from source code.
* You may modify this file by translating the extracted messages.
*
* Each array element represents the translation (value) of a message (key).
* If the value is empty, the message is considered as not translated.
* Messages that no longer need translation will have their translations
* enclosed between a pair of '@@' marks.
*
* Message string can be used with plural forms format. Check i18n section
* of the guide for details.
*
* NOTE: this file must be saved in UTF-8 encoding.
*/
return [
    'Thai' => 'tailandês',
    'Arabic' => 'árabe',
    'Chinese' => 'chinês',
    'Czech' => 'Checo',
    'Dutch' => 'holandês',
    'English' => 'Inglês',
    'French' => 'francês',
    'German' => 'alemão',
    'Greek' => 'grego',
    'Hindi' => 'hindi',
    'Indonesian' => 'indonésio',
    'Italian' => 'italiano',
    'Japanese' => 'japonês',
    'Korean' => 'coreano',
    'Persian' => 'persa',
    'Polish' => 'polonês',
    'Portuguese' => 'Português',
    'Russian' => 'russo',
    'Spanish' => 'espanhol',
    'Swedish' => 'sueco',
    'Vietnamese' => 'vietnamita',
];