<?php
/**
* Message translations.
*
* This file is automatically generated by 'yii translate' command.
* It contains the localizable messages extracted from source code.
* You may modify this file by translating the extracted messages.
*
* Each array element represents the translation (value) of a message (key).
* If the value is empty, the message is considered as not translated.
* Messages that no longer need translation will have their translations
* enclosed between a pair of '@@' marks.
*
* Message string can be used with plural forms format. Check i18n section
* of the guide for details.
*
* NOTE: this file must be saved in UTF-8 encoding.
*/
return [
    'Arabic' => 'Arabisch',
    'Chinese' => 'Chinesisch',
    'Czech' => 'tschechisch',
    'Dutch' => 'Niederländer',
    'English' => 'Englisch',
    'French' => 'Französisch',
    'German' => 'Deutsche',
    'Greek' => 'griechisch',
    'Hindi' => 'Hindi',
    'Indonesian' => 'Indonesisch',
    'Italian' => 'Italienisch',
    'Japanese' => 'Japanisch',
    'Korean' => 'Koreanisch',
    'Persian' => 'Persisch',
    'Polish' => 'Polieren',
    'Portuguese' => 'Portugiesisch',
    'Russian' => 'Russisch',
    'Spanish' => 'Spanisch',
    'Swedish' => 'Schwedisch',
    'Thailand' => 'Thailand',
    'Vietnamese' => 'Vietnamesisch',
];