<?php
/**
* Message translations.
*
* This file is automatically generated by 'yii translate' command.
* It contains the localizable messages extracted from source code.
* You may modify this file by translating the extracted messages.
*
* Each array element represents the translation (value) of a message (key).
* If the value is empty, the message is considered as not translated.
* Messages that no longer need translation will have their translations
* enclosed between a pair of '@@' marks.
*
* Message string can be used with plural forms format. Check i18n section
* of the guide for details.
*
* NOTE: this file must be saved in UTF-8 encoding.
*/
return [
    'Thai' => 'थाई',
    'Arabic' => 'अरबी',
    'Chinese' => 'चीनी',
    'Czech' => 'चेक',
    'Dutch' => 'डच',
    'English' => 'अंग्रेज़ी',
    'French' => 'फ्रांसीसी',
    'German' => 'जर्मन',
    'Greek' => 'यूनानी',
    'Hindi' => 'हिंदी',
    'Indonesian' => 'इन्डोनेशियाई',
    'Italian' => 'इतालवी',
    'Japanese' => 'जापानी',
    'Korean' => 'कोरियाई',
    'Persian' => 'फ़ारसी',
    'Polish' => 'पोलिश',
    'Portuguese' => 'पुर्तगाली',
    'Russian' => 'रूसी',
    'Spanish' => 'स्पैनिश',
    'Swedish' => 'स्वीडिश',
    'Vietnamese' => 'वियतनामी',
];