<?php
/**
* Message translations.
*
* This file is automatically generated by 'yii translate' command.
* It contains the localizable messages extracted from source code.
* You may modify this file by translating the extracted messages.
*
* Each array element represents the translation (value) of a message (key).
* If the value is empty, the message is considered as not translated.
* Messages that no longer need translation will have their translations
* enclosed between a pair of '@@' marks.
*
* Message string can be used with plural forms format. Check i18n section
* of the guide for details.
*
* NOTE: this file must be saved in UTF-8 encoding.
*/
return [
    'Arabic' => '아라비아 말',
    'Chinese' => '중국말',
    'Hindi' => '힌디 어',
    'Japanese' => '일본어',
    'Korean' => '한국어',
    'Portuguese' => '포르투갈 인',
    'Dutch' => '네덜란드 사람',
    'English' => '영어',
    'French' => '프랑스 국민',
    'German' => '독일 사람',
    'Italian' => '이탈리아 사람',
    'Russian' => '러시아인',
    'Spanish' => '스페인 사람',
    'Persian' => '페르시아 인',
    'Polish' => '광택',
];
